version: 2

models:
  - name: customers
    description: "Staging table for customers data"
    
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - not_null
          - unique